From nvidia/cuda:11.3.0-devel-ubuntu20.04

RUN apt-get update &&\
	apt-get install -y \
	openssl \
	ca-certificates \
	net-tools \
	build-essential \
	git \
	locales \
	sudo \
	whois \
	dumb-init \
	vim \
	curl \
	wget &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LANGUAGE   en_US:en
ENV LC_ALL     en_US.UTF-8
ENV TZ         Asia/Tokyo

ARG CODE="https://github.com/cdr/code-server/releases/download/v3.12.0/code-server-3.12.0-linux-amd64.tar.gz"

RUN sudo mkdir -p /opt/code-server &&\
	wget -O /tmp/code-server.tar.gz $CODE &&\
	tar zxvf /tmp/code-server.tar.gz -C /opt/code-server --strip-components 1 &&\
	rm /tmp/code-server.tar.gz
ENV PATH $PATH:/opt/code-server

COPY ./entrypoint.sh /entrypoint.sh

ENV VSCODE_USER       vscode
ENV VSCODE_PASSWORD   passwd
ENV VSCODE_GROUP      vscode
ENV VSCODE_HOME       /home/vscode
ENV VSCODE_UID        1000
ENV VSCODE_GID        1000
ENV VSCODE_GRANT_SUDO nopass
ENV VSCODE_PORT       8192

RUN groupadd -f -g $VSCODE_GID $VSCODE_GROUP &&\
    useradd -d $VSCODE_HOME -u $VSCODE_UID -g $VSCODE_GID -s /bin/bash $VSCODE_USER

EXPOSE 8192
VOLUME /home/vscode

ENTRYPOINT ["/entrypoint.sh"]
